### ISSUE TITLE
 OpenCore 0.6.9 存在关机不断电问题

### ISSUE THREAD

**Issue by xiaoxinxing12** [jerryhan77/dell-optiplex-7080mff-opencore#1]
OpenCore 0.6.9 存在关机不断电问题

7080MFF  I7 10700T   三星内存  三星硬盘

新版是否已解决！

**Comment by jerryhan77** [comment]
从初期安装就没有这方面的问题，关机/重启和休眠都正常。
检查一下你的BIOS设置，或更新到我当前的最新版本看看。
