### ISSUE TITLE
请问12.3.1系统是否已经解决了无法睡眠，屏幕显示等问题？

### ISSUE THREAD

**Issue by monuo1984** [jerryhan77/dell-optiplex-7080mff-opencore#10]
如题，我关机时还会出现紫屏。

**Comment by jerryhan77** [comment]
睡眠我最近没有测试，不过关机和重启肯定是完全正常的。
你可以尝试修改USBMap，因为我的机器后面还有一个Type-C口，而你的机器可能因为缺少这个设备而产生休眠问题。

**Comment by monuo1984** [comment]
感谢，我已经使用了你提供的EFI，目前没什么问题。就发现了一次睡眠唤醒失败的情况。
