### ISSUE TITLE
关于type-c口的速度问题

### ISSUE THREAD

**Issue by vegeta0816** [jerryhan77/dell-optiplex-7080mff-opencore#11]
你好，请问为什么tpye-c口正反插速度不一样呢，一边是10g一边只有480m，这个是dell这款机器的type-c接口设定问题吗？

**Comment by jerryhan77** [comment]
我测试了前面版的C口，非常正常，没有发现你描述的问题。
你可以尝试安装你的机器配置重做USBMap，因为我的机器后面还有一个C口，而你的机器可能缺少这个设备而产生问题。

**Comment by vegeta0816** [comment]
好的，也有可能是你扩展了另外一个c口导致的问题，我回头自己定制下看看，谢谢

**Comment by vegeta0816** [comment]
请问你买的typec扩展型号是不是R9J4K，是不是可以视频输出 ，支持4k60hz吗？

**Comment by jerryhan77** [comment]
是R9J4K, 没测试是否支持4K60Hz，应该可以。
