### ISSUE TITLE
使用最新版本能正常关机，但不能休眠

### ISSUE THREAD

**Issue by xiaoxinxing12** [jerryhan77/dell-optiplex-7080mff-opencore#3]
I7 10700T  三星 970  三星内存
使用最新版本能正常关机了，但不能休眠了

**Comment by woodencow** [comment]
关闭tpm可以正常睡眠，打开tpm睡眠会自动重启

**Comment by jerryhan77** [comment]
确实不兼容TPM，在我另外一台黑苹果上，为了DualBoot Windows 11， 我在MacOS里禁用睡眠。
