### ISSUE TITLE
感谢分享efi，不过我无法安装

### ISSUE THREAD

**Issue by tygh147852** [jerryhan77/dell-optiplex-7080mff-opencore#6]
机器一样，配置一样，bios设置一样
以为bios版本升级原因导致不能安装，后面回到旧版1.5.1
又换了内存和硬盘，还是一样，安装界面进度条走不到一半就卡住了
因为显示器是hdmi，以为是dp转hdmi导致，又买了一个原装hdmi扩展端口
还是不行，能否棒棒我

**Comment by jerryhan77** [comment]
安装的时候先把USBMap关闭，或者将一些定制简化，安装成功后再进行定制。
也可以先用早期版本安装Big Sur。因为我没有验证过直接安装monterey。
