### ISSUE TITLE
求救：同款机器，卡在Apple16X50ACPI2和UART上

### ISSUE THREAD

**Issue by JiangLennon** [jerryhan77/dell-optiplex-7080mff-opencore#9]
![1](https://user-images.githubusercontent.com/50038241/162612080-1e57e8bf-0715-49d1-b392-4fd849493e06.jpg)

**Comment by jerryhan77** [comment]
安装的时候先把USBMap关闭，或者将一些定制简化，安装成功后再进行定制。
也可以先用早期版本安装Big Sur。因为我没有验证过直接安装monterey。
